# Generated by Django 5.2.13 on 2026-04-24 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=120, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('specialty', models.CharField(blank=True, max_length=120, verbose_name='spécialité')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Compte utilisateur associé (pour login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'technicien',
                'verbose_name_plural': 'techniciens',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
