# Generated by Django 5.2.13 on 2026-04-24 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('STATUS', 'Changement de statut'), ('ASSIGN', 'Affectation'), ('COMMENT', 'Commentaire'), ('CLOSE', 'Clôture'), ('REOPEN', 'Réouverture'), ('DELETE', 'Suppression'), ('OTHER', 'Autre')], default='OTHER', max_length=10, verbose_name='action')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='tickets.ticket', verbose_name='demande')),
            ],
            options={
                'verbose_name': "entrée d'historique",
                'verbose_name_plural': 'historique',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='history_his_created_df6d62_idx')],
            },
        ),
    ]
