# Generated by Django 5.2.13 on 2026-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SAVIO', max_length=100, verbose_name="nom de l'application")),
                ('site_tagline', models.CharField(blank=True, default='Gestion du Service Après-Vente', max_length=200, verbose_name='slogan')),
                ('support_email', models.EmailField(blank=True, default='support@savio.local', max_length=254, verbose_name='email de support')),
                ('primary_color', models.CharField(default='#4154f1', max_length=16, verbose_name='couleur principale')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='notifications internes activées')),
                ('allow_self_registration', models.BooleanField(default=False, verbose_name='inscription publique autorisée')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paramètre général',
                'verbose_name_plural': 'paramètres généraux',
            },
        ),
        migrations.CreateModel(
            name='PriorityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=80, verbose_name='libellé')),
                ('color', models.CharField(default='#0dcaf0', max_length=16, verbose_name='couleur')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'priorité',
                'verbose_name_plural': 'priorités',
                'ordering': ('order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='StatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=80, verbose_name='libellé')),
                ('color', models.CharField(default='#6c757d', max_length=16, verbose_name='couleur')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'statut',
                'verbose_name_plural': 'statuts',
                'ordering': ('order', 'label'),
            },
        ),
    ]
