# Generated by Django 5.2.13 on 2026-04-24 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('technicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='référence')),
                ('subject', models.CharField(max_length=200, verbose_name='objet')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('OPEN', 'Ouvert'), ('PROG', 'En cours'), ('PEND', 'En attente'), ('RESO', 'Résolu'), ('CLOS', 'Clôturé'), ('CANC', 'Annulé')], default='NEW', max_length=4, verbose_name='statut')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('NORM', 'Normale'), ('HIGH', 'Haute'), ('URG', 'Urgente')], default='NORM', max_length=4, verbose_name='priorité')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='clôturé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to='technicians.technician', verbose_name='technicien assigné')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'demande SAV',
                'verbose_name_plural': 'demandes SAV',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='message')),
                ('is_internal', models.BooleanField(default=False, help_text='Non visible par les utilisateurs simples', verbose_name='note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-created_at'], name='tickets_tic_created_c2132d_idx'),
        ),
    ]
