# Generated by Django 5.2.13 on 2026-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IND', 'Particulier'), ('COM', 'Entreprise')], default='IND', max_length=3, verbose_name='type')),
                ('last_name', models.CharField(max_length=120, verbose_name='nom / raison sociale')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='prénom')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='société')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='code postal')),
                ('country', models.CharField(blank=True, default='France', max_length=120, verbose_name='pays')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('last_name', 'first_name'),
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='clients_cli_last_na_198e2f_idx')],
            },
        ),
    ]
